# Generated by Django 2.1.3 on 2018-11-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmaku_robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotsettings',
            name='value',
            field=models.CharField(max_length=1024, verbose_name='value'),
        ),
    ]
